# Generated by Django 4.2.24 on 2025-09-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0002_mappingconfig_tablemapping_columnmapping"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sync_key_column",
                    models.CharField(
                        help_text="The column used to detect new/updated rows (e.g., 'id' or 'updated_at').",
                        max_length=255,
                    ),
                ),
                (
                    "last_sync_value",
                    models.CharField(
                        blank=True,
                        help_text="The last value of the sync key that was processed.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mapping_config",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_schedule",
                        to="mapping.mappingconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
