# Generated by Django 4.2.24 on 2025-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConnectorPlugin",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="A user-friendly name for the connector, e.g., 'PostgreSQL'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "plugin_key",
                    models.CharField(
                        help_text="The internal key for the plugin, e.g., 'postgres'.",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable this connector across the application.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connector Plugin",
                "verbose_name_plural": "Connector Plugins",
            },
        ),
    ]
