# Generated by Django 4.2.24 on 2025-09-18 18:45

from django.db import migrations

def populate_connector_plugins(apps, schema_editor):
    """
    Creates the initial ConnectorPlugin records for the built-in connectors.
    """
    ConnectorPlugin = apps.get_model('connectors', 'ConnectorPlugin')

    plugins = [
        {'plugin_key': 'postgres', 'name': 'PostgreSQL', 'is_enabled': True},
        {'plugin_key': 'mysql', 'name': 'MySQL', 'is_enabled': True},
    ]

    for plugin_data in plugins:
        ConnectorPlugin.objects.update_or_create(
            plugin_key=plugin_data['plugin_key'],
            defaults=plugin_data
        )

def remove_connector_plugins(apps, schema_editor):
    """
    Removes the initial ConnectorPlugin records.
    (This is the reverse operation)
    """
    ConnectorPlugin = apps.get_model('connectors', 'ConnectorPlugin')
    ConnectorPlugin.objects.filter(plugin_key__in=['postgres', 'mysql']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_connector_plugins, remove_connector_plugins),
    ]
