# Generated by Django 4.2.24 on 2025-09-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_snapshots",
                        to="core.connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Snapshot",
                "verbose_name_plural": "Schema Snapshots",
                "ordering": ["-created_at"],
            },
        ),
    ]
