# Generated by Django 4.2.24 on 2025-09-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_configs",
                        to="core.project",
                    ),
                ),
                (
                    "source_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_mappings",
                        to="core.connection",
                    ),
                ),
                (
                    "target_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_mappings",
                        to="core.connection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TableMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_table_name", models.CharField(max_length=255)),
                ("target_table_name", models.CharField(max_length=255)),
                ("include_in_migration", models.BooleanField(default=True)),
                (
                    "mapping_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_mappings",
                        to="mapping.mappingconfig",
                    ),
                ),
            ],
            options={
                "unique_together": {("mapping_config", "source_table_name")},
            },
        ),
        migrations.CreateModel(
            name="ColumnMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_column_name", models.CharField(max_length=255)),
                ("target_column_name", models.CharField(max_length=255)),
                ("target_data_type", models.CharField(max_length=100)),
                ("transform_expression", models.TextField(blank=True, null=True)),
                ("is_ignored", models.BooleanField(default=False)),
                (
                    "table_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_mappings",
                        to="mapping.tablemapping",
                    ),
                ),
            ],
            options={
                "unique_together": {("table_mapping", "source_column_name")},
            },
        ),
    ]
