# Generated by Django 4.2.24 on 2025-09-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0002_mappingconfig_tablemapping_columnmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnmapping",
            name="is_primary_key",
            field=models.BooleanField(default=False),
        ),
    ]
